
# 한줄 주석

# 해당 파일에 설정을 작성 시 프로젝트 전반적으로 설정이 적용된다

# 애플리케이션 프로그램 이름. 나중에 서버 돌릴 때 뜨는 거

spring.application.name=demoProject1

# 톰캣의 포트번호인 8080을 그냥 80으로 바꾼다. 80번은 HTTP 프로토콜의 기본 포트번호라 localhost:8080 대신에 localhost: 라고 하면 자동으로 80이 된다
# 브라우저에서 포트번호 없이 접속 가능하다

server.port = 80 
# 이제 아예 포트번호를 안 쓰고 서버를 돌릴 것임




# Spring DevTools (새로고침 및 서버의 재시작에 대한 설정)

spring.devtools.livereload.enabled=true
# 브라우저에서 자기가 알아서 강력 새로고침

spring.devtools.restart.enabled=true
#코드 변경 시 서버를 자동 재시작



spring.thymeleaf.cache=false
# 타입리프 (뷰단을 담당하는 엔진)의 캐시를 비활성화 (html의 파일 바꾸면 바로 변경을 확인 가능)


#로그 레벨 지정
logging.level.edu.kh.demo=debug
# 로그 레벨 6단계 => 

# 1단계 - TRACE: 가장 상세한 로그레벨, 최대한 오류나 진행 상황을 자세히 알고싶어
# 2단계 - DEBUG: 디버깅에 유용한 정보를 저장하며 값을 추적하고싶다 (TRACE보다는 덜 상세)
# 3단계 - INFO: 일반적인 정보 메시지 기록 (defualt of spring boot)
# 4단계 - WARN: 경고 메시지가 나올때만 기록
# 5단계 - ERROR: 오류 메시지를 기록, 즉 심각한 문제 발생 시에만 기록
# 6단계 - FATAL: 가장 심각한 오류로 개발자가 무언가를 할 수 없는 경우에만 기록

# 이제는 debug부터 아랫 단계까지 전부 사용 가능 
# 해당 파일이 있는 패키지 이름과 동일한지 봐야 함 (DemoProject1Application.java 파일의 경로)


