spring.application.name=boardProject-boot

server.port= 80

# 이제 아예 포트번호를 안 쓰고 서버를 돌릴 것임

# Spring DevTools (새로고침 및 서버의 재시작에 대한 설정) (처음에 라이브러리  추가했었음)
spring.devtools.livereload.enabled=true
# 브라우저에서 자기가 알아서 강력 새로고침

spring.devtools.restart.enabled=true
#코드 변경 시 서버를 자동 재시작

spring.thymeleaf.cache=false
# 타입리프 (뷰단을 담당하는 엔진)의 캐시를 비활성화 (html의 파일 바꾸면 바로 변경을 확인 가능)


#로그가 찍히는 범위 지정 
logging.level.edu.kh.project=debug
# 패키지 이름에 따라 이 수식을 바꿔야 한다


# 이제는 debug부터 아랫 단계까지 전부 사용 가능 
# 해당 파일이 있는 패키지 이름과 동일한지 봐야 함 (DemoProject1Application.java 파일의 경로)


#url에 jsessionid가 보여질 때 설정
server.servlet.session.tracking-modes=cookie
# 서버가 클라이언트를 식별하기 위해 생성한 세션 ID
# 원래 쿠키에 저장되어야 하는데 브라우저에서 쿠키 사용이 안되면 URL에 잘못 저장되어 오류가 발생

#보통 세션 객체가 생성될 때 자동으로 만들어진다
#기본적으로 쿠키를 통해 클라이언트 정보를 저장한다



